
$script_mysql = <<-SCRIPT
  apt update -y && \
  apt install -y mysql-server-5.7 && \
  mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysqldb" do |mysql|
    # give vm an IP
    # config.vm.network "private_network", ip: "192.168.50.4"
    # set dhcp
    # config.vm.network "private_network", type: "dhcp"
    # public network
    mysql.vm.network "public_network", ip: "192.168.15.51"

    mysql.vm.provision "shell", 
      inline: "cat /configs/id_bionic.pub >> .ssh/authorized_keys"
        
    mysql.vm.provision "shell", inline: $script_mysql
    
    mysql.vm.provision "shell", 
      inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    
    mysql.vm.provision "shell", 
      inline: "systemctl restart mysql"

    # add a synced folder
    mysql.vm.synced_folder "./configs", "/configs"
    # disable default synced folder
    mysql.vm.synced_folder ".", "/vagrant", disabled: true 
  end

  config.vm.define "phpweb" do |phpweb|
    # forward windows port to VM
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    # public network
    phpweb.vm.network "public_network", ip: "192.168.15.50"
    phpweb.vm.provision "shell", 
      inline: "apt update && apt install -y puppet"
    
    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end

end
